Adds method to user model for creation and some tests to check it
wolox-training/cha-express-js pull request #3
Opened 2018-07-31 21:57 UTC by christiangelone

## Summary

 * Adds functionality for creation of user, in a backend perspective
 * Tests creation of users for creation of use

## Things to consider in the future:
  * Creation of users should be db / framework agnostic 

## Trello Card

https://trello.com/c/U88apt6L

2018-08-01 16:49 UTC, gonziesc requested changes

2018-08-01 16:49 UTC, gonziesc commented on app/controllers/users.js
> +  User.isPwdLengthGreater(userObj, 8)
you have to return the promise

2018-08-01 16:49 UTC, gonziesc commented on app/controllers/users.js
> +      bcrypt.hash(userObj.password, 10).then(hashedPwd => {
you dont need to wait for the user.ispwdfLengthGreater for calling this one, you can do a promise.all with both

2018-08-01 16:49 UTC, gonziesc commented on app/controllers/users.js
> +        User.createModel(userObj)
return promise. also, i would call it just create

2018-08-01 16:49 UTC, gonziesc commented on app/controllers/users.js
> +            if (err.name === 'SequelizeValidationError') {
you can use the error manager for this

2018-08-01 16:49 UTC, gonziesc commented on app/controllers/users.js
> +      const someErrors = [
same here

2018-08-01 16:49 UTC, gonziesc commented on app/controllers/users.js
> +          error: 'password should be greater than or equal to 8 characters'
abstract the message to other part of the code, like the error manager.

2018-08-01 16:49 UTC, gonziesc commented on app/models/index.js
> +sequelize.authenticate().then(() => {
delete this

2018-08-01 16:49 UTC, gonziesc commented on app/models/user.js
> +          isEmail: { args: true, msg: 'not a valid email' },
lets validate this before going to the database

2018-08-01 16:49 UTC, gonziesc commented on app/models/user.js
> +          len: { args: [0, 100], msg: 'email cant be bigger than 100 characters' }
same this

2018-08-01 16:49 UTC, gonziesc commented on app/models/user.js
> +    return new Promise((res, rej) => {
this is synchronous, there is no need to make a promise for this

2018-08-01 16:49 UTC, gonziesc commented on app/models/user.js
> +  User.createModel = user => {
this method is doing nothing

2018-08-01 16:49 UTC, gonziesc commented on test/controllers/user.test.js
> +        res.should.have.status(201);
validate that the user is created

2018-08-01 16:49 UTC, gonziesc commented on test/controllers/user.test.js
> +        err.response.should.be.json;
validate message

2018-08-01 16:49 UTC, gonziesc commented on test/controllers/user.test.js
> +        err.response.should.be.json;
same

2018-08-01 16:49 UTC, gonziesc commented on test/controllers/user.test.js
> +        err.response.should.be.json;
same

2018-08-01 16:49 UTC, gonziesc commented on test/services/user.test.js
> +const assert = require('chai').assert;
delete this file

2018-08-02 13:51 UTC, gonziesc requested changes

2018-08-02 13:51 UTC, gonziesc commented on app/controllers/users.js
> +  bcrypt
return promise

2018-08-02 13:51 UTC, gonziesc commented on app/controllers/users.js
> +      User.createModel(userObj)
return promise

2018-08-02 13:51 UTC, gonziesc commented on app/models/user.js
> +  User.createModel = user => {
this is useless

2018-08-02 13:51 UTC, gonziesc commented on app/routes.js
> +  app.use((err, req, res, next) => {
do you need this?

2018-08-02 13:51 UTC, gonziesc commented on test/controllers/user.test.js
> +        res.should.have.status(201);
check it in the database

2018-08-03 15:45 UTC, christiangelone commented on app/routes.js
> +  app.use((err, req, res, next) => {
Yes to process any validation issue

2018-08-03 15:46 UTC, christiangelone commented
All done!

2018-08-03 16:00 UTC, gonziesc requested changes

2018-08-03 16:00 UTC, gonziesc commented on app/controllers/users.js
> +  bcrypt
again

2018-08-03 16:00 UTC, gonziesc commented on test/controllers/user.test.js
> +        res.should.have.status(201);
same

2018-08-03 16:00 UTC, gonziesc commented on test/models/user.test.js
> +        User.findById(createdUser.id)
move this validation to the create endpoint, and delete this file

2018-08-03 16:01 UTC, gonziesc commented
Lasts comments!

2018-08-03 21:04 UTC, gonziesc requested changes

2018-08-03 21:04 UTC, gonziesc commented on app/controllers/users.js
> +  bcrypt
return the bcrypt promise

2018-08-03 21:04 UTC, gonziesc commented on app/controllers/users.js
> +  bcrypt
return the bcrypt promise

2018-08-03 21:04 UTC, gonziesc commented on app/errors.js
> +exports.notFound = resource => internalError(`${resource} not found`, exports.NOT_FOUND);
what is this doing here?

2018-08-03 21:04 UTC, gonziesc commented on test/controllers/user.test.js
> +        res.should.have.status(201);
the idea was that you validate here with the db, not with another endpoint

2018-08-06 13:51 UTC, gonziesc requested changes

2018-08-06 13:51 UTC, gonziesc commented on app/controllers/users.js
> +  User.find({
return

2018-08-06 13:51 UTC, gonziesc commented on app/controllers/users.js
> +  const anId = req.params.id;
just id for name

2018-08-06 14:38 UTC, gonziesc approved these changes

2018-08-06 16:20 UTC, merged