Feature admins create
wolox-training/cha-express-js pull request #8
Opened 2018-08-09 14:54 UTC by christiangelone

## Summary
 * Adds endpoint for creation of admins
 * Adds security for admin creation (only logged admins can create)
 * Adds input validations for admin creation (same as regular users)
 * If user exists as regular it becomes admin

## Known Issues
 * No Issues

## Trello Card
  * https://trello.com/c/Uti3HuZg

2018-08-09 16:08 UTC, gonziesc requested changes

2018-08-09 16:08 UTC, gonziesc commented on app/controllers/admins.js
> +      return User.createAdmin(adminObj);
chain this promise

2018-08-09 16:08 UTC, gonziesc commented on migrations/migrations/20180808201537-add_role_column_to_user.js
> +    return [
why list?

2018-08-09 16:08 UTC, gonziesc commented on test/controllers/admin.test.js
> +        })
chain promises

2018-08-09 16:08 UTC, gonziesc commented on test/controllers/admin.test.js
> +          return request.get(`/users/${res.body.id}`);
chain promises

2018-08-09 16:08 UTC, gonziesc commented on test/controllers/admin.test.js
> +          return UserRequests.signInAsDefaultAdmin();
chain promises

2018-08-09 16:08 UTC, gonziesc commented on test/controllers/admin.test.js
> +          return UserRequests.signInAsDefaultAdmin();
chain

2018-08-09 16:08 UTC, gonziesc commented on test/controllers/admin.test.js
> +        })
chain

2018-08-09 16:08 UTC, gonziesc commented on test/helpers/user_requests.js
> +      return resToken.body;
why?

2018-08-09 16:08 UTC, gonziesc commented on test/helpers/user_requests.js
> +const chai = require('chai');
why are you validating things in a helpers file?

2018-08-09 16:08 UTC, gonziesc commented on app/controllers/admins.js
> +exports.create = (req, res, next) => {
mmm, this is too much duplicated logic, why dont you use the create endpoint?

2018-08-09 17:40 UTC, christiangelone commented on migrations/migrations/20180808201537-add_role_column_to_user.js
> +    return [
because in that way you can add multiple commands

2018-08-10 20:12 UTC, gonziesc requested changes
little changes

2018-08-10 20:12 UTC, gonziesc commented on app/controllers/users.js
> +        return persist(userObj);
nest promises

2018-08-10 20:12 UTC, gonziesc commented on migrations/migrations/20180808201537-add_role_column_to_user.js
> +    return [
then do a promise all!

2018-08-10 21:43 UTC, gonziesc requested changes

2018-08-10 21:43 UTC, gonziesc commented on app/controllers/users.js
> +        JwtService.encode({ id: user.id, role: user.role })
return

2018-08-10 21:56 UTC, gonziesc approved these changes

2018-08-10 21:57 UTC, merged